project:
  type: book
  output-dir: docs

book:
  title: "Estatisca Resumida"
  author: "Thalis Rebouças"
  cover-image: cover.jpg
  favicon: cover.jpg
  page-footer:
    left: |
      Estatística Resumida BOOK (1e) por  Thalis Rebouças.
    right: |
      Esse livro foi feito em <a href="https://quarto.org/">Quarto</a>.
  site-url: https://thalisreboucas.com.br
  repo-url: https://github.com/thalisreboucas/Estatistica_Resumida_Book
  repo-branch: main
  chapters:
    - index.qmd
    - 02-descritiva.qmd
    - 03-correlacao.qmd
    - 04-inferencia.qmd
    - 05-nao_parametrica.qmd
    - 06-regressao.qmd
    - 07-multivariada.qmd
    - 08-amostragem.qmd
    - 09-graficos.qmd
    - 10-referencia.qmd


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual